services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dd
      - POSTGRES_DB=kerp #optional (specify default database instead of $POSTGRES_USER)
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=js@js.com
      - PGADMIN_DEFAULT_PASSWORD=dd
    ports:
      - "5050:80"
volumes:
  postgres: